### ISSUE TITLE
CCE in XtextReconcilerJob

### ISSUE THREAD

**Issue by LorenzoBettini** [LorenzoBettini/jbase#131]
Given this valid program (in any of the Jbase test/example languages)

```java
System.out.println("");
```

Modifying the program as follows

```java
System.out.println("h");
```

shows a dialog with an CCE in XtextReconcilerJob. The stacktrace does not show anything from Jbase, so it looks like it's a problem in Xbase (see also https://github.com/eclipse/xtext/issues/2323 and similarly https://github.com/eclipse/xtext/issues/2345).

This is the stacktrace

```
java.lang.ClassCastException: class org.eclipse.xtext.nodemodel.impl.LeafNode cannot be cast to class org.eclipse.xtext.nodemodel.impl.CompositeNode (org.eclipse.xtext.nodemodel.impl.LeafNode and org.eclipse.xtext.nodemodel.impl.CompositeNode are in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @1cfef594)
	at org.eclipse.xtext.xbase.parser.LookAheadPreservingNodeModelBuilder.replaceAndTransferLookAhead(LookAheadPreservingNodeModelBuilder.java:41)
	at org.eclipse.xtext.xbase.parser.TokenSequencePreservingPartialParsingHelper.reparse(TokenSequencePreservingPartialParsingHelper.java:127)
	at org.eclipse.xtext.parser.antlr.AbstractAntlrParser.doReparse(AbstractAntlrParser.java:139)
	at org.eclipse.xtext.parser.AbstractParser.reparse(AbstractParser.java:51)
	at org.eclipse.xtext.resource.XtextResource.update(XtextResource.java:266)
	at org.eclipse.xtext.ui.editor.reconciler.XtextDocumentReconcileStrategy.doReconcile(XtextDocumentReconcileStrategy.java:183)
	at org.eclipse.xtext.ui.editor.reconciler.XtextDocumentReconcileStrategy.reconcile(XtextDocumentReconcileStrategy.java:91)
	at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler.doRun(XtextReconciler.java:457)
	at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler.access$3(XtextReconciler.java:437)
	at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler$1.process(XtextReconciler.java:371)
	at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler$1.process(XtextReconciler.java:1)
	at org.eclipse.xtext.util.concurrent.IUnitOfWork$Void.exec(IUnitOfWork.java:38)
	at org.eclipse.xtext.resource.OutdatedStateManager.exec(OutdatedStateManager.java:70)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.modify(XtextDocument.java:432)
	at org.eclipse.xtext.ui.editor.model.XtextDocument.internalModify(XtextDocument.java:165)
	at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler.run(XtextReconciler.java:368)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by LorenzoBettini** [comment]
More details can be found here https://github.com/eclipse/xtext/issues/2323 and a possible solution here https://github.com/eclipse/xtext/issues/2323
